name: base
dependencies:
  - python=3.10.14
  - pip=24.0
  - conda-tree=1.1.0
  - ipython=8.26.0
  - libgomp=13.2.0
  - mamba=1.5.8
  - seaborn=0.13.2
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - transformers=4.42.3
  - wandb=0.16.6
  - pip:
      - accelerate==0.32.1
      - conda-minify==0.1.2
      - conda-pip-minimal==0.2.1
      - evaluate==0.4.2
      - ferret-xai==0.4.2
      - fqdn==1.5.1
      - gender-guesser==0.4.0
      - inquirerpy==0.3.4
      - isoduration==20.11.0
      - notebook==7.2.1
      - pipdeptree==2.23.1
      - rich==13.7.1
      - shellingham==1.5.4
      - uri-template==1.3.0
      - webcolors==24.6.0

